---
- name: "node configuration"
  template:
    src: "{{ item }}.j2"
    dest: "/etc/munin/{{ item }}"
  with_items: "{{ munin_node_files }}"
  when: "is_client is defined and 'true' in is_client"
  notify:
    - restart munin-node service
  tags:
     - configure

- name: "server configuration"
  template:
    src: "munin.conf.j2"
    dest: "/etc/munin/munin.conf"
  when: "is_server is defined and 'true' in is_server"
  tags:
     - configure
<<<<<<< HEAD
=======

>>>>>>> d5a6902bf2a9736697c2279aaed89667aead45b3
