---
- name: "node configuration"
  template:
    src: "{{ item }}.j2"
    dest: "/etc/munin/{{ item }}"
  with_items: "{{ munin_node_files }}"
  when: "is_client is defined and 'true' in is_client"
  notify:
    - restart munin-node service
  tags:
     - configure
     - configure_node

- name: "create munin node vars directory"
  file:
    path: "/etc/munin/plugin-conf.d/"
    state: directory
  when: "is_client is defined and 'true' in is_client"
  tags:
     - configure
     - configure_node

- name: "munin node vars configuration"
  template:
    src: munin-node.j2
    dest: "/etc/munin/plugin-conf.d/munin-node"
  when: "is_client is defined and 'true' in is_client"
  notify:
    - restart munin-node service
  tags:
     - configure
     - configure_node

- name: "server configuration"
  template:
    src: "munin.conf.j2"
    dest: "/etc/munin/munin.conf"
  when: "is_server is defined and 'true' in is_server"
  tags:
     - configure
     - configure_server
