---
- name: Install munin client
  apt:
    name: munin-node
    update_cache: yes
    cache_valid_time: 3600
  when: "is_client is defined and 'true' in is_client"
  tags:
    - install
    - install_client

- name: Install munin Server
  apt:
    name: munin
    update_cache: yes
    cache_valid_time: 3600
  when: "is_client is defined and 'true' in is_server"
  tags:
    - install
    - install_server
