---
- name: Install dependances
  apt:
    name  : "{{ item }}"
    state : present
  with_items: "{{ munin_dependances_packages }}"

- name: 'Include install'
  include: install.yml
  tags:
    - install
    - install_client
    - install_server

- name: 'Include Configure'
  include: configure.yml
  tags:
    - install
    - install_client
    - install_server

- name: 'Include plugins'
  include: plugins.yml

- name: 'Include Apache'
  include: apache.yml

- name: 'Include MySQL'
  include: mysql.yml

- name: 'Include Varnish'
  include: varnish.yml

- name: 'Include Memcached'
  include: memcached.yml
