---
- name: enable define plugins
  file:
    src: "/usr/share/munin/plugins/{{ item }}"
    dest: "/etc/munin/plugins/{{ item }}"
    state: link
  with_items: "{{ munin_node_plugins_add }}"
  tags:
    - install
    - install_client
   
- name: disable define plugins
  file:
    src: "/usr/share/munin/plugins/{{ item }}"
    dest: "/etc/munin/plugins/{{ item }}"
    state: absent
  with_items: "{{ munin_node_plugins_remove }}"
  tags:
    - install
    - install_client
   

