---

- name: enable varnish plugins
  copy:
    src: "plugins/varnish4_"
    dest: "/usr/share/munin/plugins/varnish4_"
    mode: 0755
  when: "is_varnish_server is defined and 'true' in is_varnish_server"
  tags:
    - munin_varnish

- name: enable varnish 4 plugins
  file:
    src: "/usr/share/munin/plugins/varnish4_"
    dest: "/etc/munin/plugins/varnish_{{ item }}"
    state: link
  with_items: "{{ munin_node_plugin_varnish }}"
  when: "is_varnish_server is defined and 'true' in is_varnish_server"
  notify:
    - restart munin-node service
  tags:
    - munin_varnish


#- name: enable varnish plugins
#  file:
#    src: "/usr/share/munin/plugins/varnish_"
#    dest: "/etc/munin/plugins/varnish_{{ item }}"
#    state: link
#  with_items: "{{ munin_node_plugin_varnish }}"
#  when: "is_varnish_server is defined and 'true' in is_varnish_server"
#  tags:
#    - munin_varnish


